check signed import
Pandora-IsoMemo/TraceR pull request #24
Opened 2024-08-01 14:23 UTC by f-lukas

https://github.com/Pandora-IsoMemo/TraceR/issues/21

2024-08-07 09:51 UTC, f-lukas commented
@arunge you can start with the review. I have to check with @jan-abel-inwt if my adjustments in the docker and jenkinsfile work. Also the pipeline is failing at the moment because the secret files are not yet uploaded to jenkins.

If you want to test it locally you can create your own key pair with your script here https://github.com/Pandora-IsoMemo/TraceR/pull/10/files. You have to place the files in `inst/app`. To test how the functionalitiy works for the deployed version, you can create an `.Renviron` file with SHINYPROXY_USERID=123.

2024-08-08 12:24 UTC, arunge requested changes
I find the if-else clauses  regarding the validation is quite nested, but I do not have a better idea right now. I just added some more comments. I fine-tuned some warnings.

In general, all was working fine! :+1:  Only the case of unsigned files locally, see below.

2024-08-08 12:24 UTC, arunge commented on R/02_importModule.R
> +    )
```suggestion
    )
  }
```

2024-08-08 12:24 UTC, arunge commented on R/02_importModule.R
> +    message <- "No signature was found in the uploaded json. File could not be verified."
```suggestion
    message <- "No signature was found in the uploaded json. Continuing without verification."
```

2024-08-08 12:24 UTC, arunge commented on R/02_importModule.R
> +  } else {
```suggestion
  } else {
  # Skip check of validity, because no signature
```

2024-08-08 12:53 UTC, f-lukas commented
Good point. I missed this case and applied your suggestions.

2024-08-20 08:00 UTC, arunge approved these changes

2024-10-17 09:54 UTC, merged